# Generated by Django 5.2.5 on 2025-08-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descripción'),
        ),
    ]
