# Generated by Django 5.2.5 on 2025-08-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='filename',
            field=models.CharField(default='default.jpg', max_length=255, verbose_name='Nombre del archivo'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='Datos de imagen'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(default='image/jpeg', max_length=50, verbose_name='Tipo de imagen'),
        ),
    ]
